"""link worker to domains

Revision ID: 2eafb51244c6
Revises: e0826a0d6eb2
Create Date: 2024-02-13 18:46:18.182399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eafb51244c6'
down_revision = 'e0826a0d6eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_worker_domain_id', 'domains', ['domain_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_worker_domain_id', type_='foreignkey')
        batch_op.drop_column('domain_id')

    # ### end Alembic commands ###
